#!/bin/bash

test_server_stdout=tests/server.stdout

function install_deps {
    pip install --user -r requirements-dev.txt
}

function run {
    PYTHONPATH=. py.test -vv --cov-report term-missing --cov m3u8 tests/
}

function main {
    install_deps
    run
    retval=$?
    return "$retval"
}

if [ -z "$1" ]; then
    main
else
    $@
fi
